const String CCLIST[128] = {"Bank Select",
"Modulation Wheel",
"Breath Controller",
"Undefined",
"Foot Pedal",
"Portamento/Glide Time",
"Data Entry (MSB)",
"MIDI Volume",
"Stereo Balance",
"Undefined",
"Pan Position / Balance",
"Expression Pedal",
"Effect Controller 1",
"Effect Controller 2",
"Undefined",
"Undefined",
"Slider, Knob or Ribbon Controller",
"Slider, Knob or Ribbon Controller",
"Slider, Knob or Ribbon Controller",
"Slider, Knob or Ribbon Controller",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Bank Select (LSB)",
"Modulation Wheel (LSB)",
"Breath Controller (LSB)",
"Undefined",
"Foot Pedal (LSB)",
"Portamento/Glide Time (LSB)",
"Data Entry (LSB)",
"Volume (LSB)",
"Balance (LSB)",
"Undefined",
"Pan Position (LSB)",
"Expression (LSB)",
"Effect Control 1 (LSB)",
"Effect Control 2 (LSB)",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Sustain Pedal On/Off",
"Portamento/Glide On/Off Switch",
"Sostenuto On/Off Switch",
"Soft Pedal On/Off Switch",
"Legato On/Off Switch",
"Hold Pedal 2",
"Sound Controller 1",
"Sound Controller 2 - Filter Resonance",
"Sound Controller 3 - Amp Envelope Decay",
"Sound Controller 4 - Amp Envelope Attack",
"Sound Controller 5 - Filter Cutoff",
"Sound Controller 6",
"Sound Controller 7",
"Sound Controller 8",
"Sound Controller 9",
"Sound Controller 10",
"General Purpose",
"General Purpose",
"General Purpose",
"General Purpose",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Undefined",
"Effect 1 Amount (Reverb)",
"Effect 2 Amount (Tremelo)",
"Effect 3 Amount (Chorus)",
"Effect 4 Amount (Detuning)",
"Effect 5 Amount (Phaser)",
"Data Bound Increment (+1)",
"Data Bound Decrement (-1)",
"NRPN LSB",
"NRPN MSB",
"1RPN LSB",
"1RPN MSB",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Undefined",
"1Channel Mute / Sound Off",
"1Reset All Controllers",
"1Local Keyboard On/Off Switch",
"1All MIDI Notes OFF",
"1OMNI Mode OFF",
"1OMNI Mode ON",
"1Mono Mode",
"1Poly Mode"};